Introduce compiler error
Using a linkedHashMap of @Composable functions results in the following error when building:

java.lang.IllegalStateException: Operation is unsupported

The error requires the @Composable annotation be used and also requires the map is operated on either with a get() or [] access or remove() call.